package com.timestr.backend.model;

public enum ActivityType {
    TASK_COMPLETED,
    COLLABORATOR_JOINED,
    DEADLINE_UPDATED,
    PROJECT_CREATED,
    TASK_CREATED,
    TASK_UPDATED,
    COLLABORATOR_INVITED,
    PROJECT_UPDATED,
    TASK_DELETED
}
